urls.py
# urls.py

from django.urls import path
from . import views 

app_name = 'calendar'
urlpatterns = [
    path('calendar/<int:year>/<int:month>/', views.monthly_calendar, name='monthly_calendar'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    # Add more URLs as needed
]

models.py
# calendar_app/models.py

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import pre_delete
from django.dispatch import receiver


class EventLink(models.Model):
    object_date = models.DateField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    # Altri campi che potresti voler aggiungere

    def __str__(self):
        return f"{self.content_object} - {self.object_date}"
    

@receiver(pre_delete)
def delete_event_link(sender, instance, **kwargs):
    try:
        # Prova a ottenere il valore del campo 'object_date'
        object_date = getattr(instance, 'date', None)

        if object_date:
            # Trova e cancella l'EventLink associato all'oggetto che sta per essere eliminato
            content_type = ContentType.objects.get_for_model(sender)
            event_link = EventLink.objects.filter(
                content_type=content_type,
                object_id=instance.id,
                object_date=object_date
            ).first()

            if event_link:
                event_link.delete()
    except Exception as e:
        # Gestisci eventuali eccezioni durante l'esecuzione
        pass

forms.py
# forms.py

from django import forms
from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'start_date', 'start_time', 'end_date', 'end_time', 'description']

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        start_time = cleaned_data.get('start_time')
        end_time = cleaned_data.get('end_time')

        if start_date and end_date and start_date > end_date:
            raise forms.ValidationError('Start date must be before the end date.')

        if start_date == end_date and start_time and end_time and start_time >= end_time:
            raise forms.ValidationError('Start time must be before the end time when the dates are the same.')

views.py
# views.py

import calendar as cal_module
from django.shortcuts import render, get_object_or_404
from .models import EventLink
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta



def monthly_calendar(request, year, month):
    # Logica per ottenere il calendario del mese
    calendar_data = cal_module.monthcalendar(year, month)

    # Logica per ottenere gli eventi del mese
    events = get_events_for_month(year, month)

    # Calcola il mese precedente
    selected_month = datetime(year, month, 1)
    prev_month = selected_month + relativedelta(months=-1)
    next_month = selected_month + relativedelta(months=+1)
    print(events)
    context = {
        'calendar': calendar_data,
        'events': events,
        'year': year,
        'month': month,
        'prev_month': prev_month,
        'next_month': next_month,
    }


    return render(request, 'calendar/monthly_calendar.html',  context)


def get_events_for_month(year, month):
    # Calcola la data di inizio e fine del mese
    start_date = date(year, month, 1)
    _, last_day = cal_module.monthrange(year, month)
    end_date = start_date + relativedelta(day=last_day)

    # Filtro per gli eventi che hanno la data uguale al mese selezionato
    events = EventLink.objects.filter(
        object_date__gte=start_date,
        object_date__lte=end_date
    )

    # Nel tuo view o context processor Django
    events_dict = {}
    for event in events:
        day_key = event.start_date.day
        if day_key not in events_dict:
            events_dict[day_key] = []
        events_dict[day_key].append(event)

    return events_dict



def get_next_month(year, month):
    current_date = datetime(year, month, 1)
    next_month = current_date + timedelta(days=cal_module.monthrange(current_date.year, current_date.month)[1])
    return next_month.year, next_month.month

def get_previous_month(year, month):
    current_date = datetime(year, month, 1)
    first_day_of_month = datetime(current_date.year, current_date.month, 1)
    previous_month = first_day_of_month - timedelta(days=1)
    return previous_month.year, previous_month.month



def event_detail(request, event_id):
    # Retrieve the event using the event_id
    event = get_object_or_404(Event, id=event_id)

    context = {
        'event': event
        }


    return render(request, 'calendar/event_detail.html', context)

templates/calendar/event_detail.html
<!-- templates/calendar/event_detail.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>{{ event.title }}</h2>
  <p><strong>Start Date:</strong> {{ event.start_date }} {{ event.start_time }}</p>
  <p><strong>End Date:</strong> {{ event.end_date }} {{ event.end_time }}</p>
  <p><strong>Description:</strong> {{ event.description }}</p>
  <!-- Add more details as needed -->
{% endblock %}

templates/calendar/monthly_calendar.html
<!-- templates/calendar/monthly_calendar.html -->

{% extends 'website/base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="d-flex justify-content-between mb-4">
    <h2>{{ month }}/{{ year }} Calendar</h2>
    <div>
      <a href="{% url 'calendar:monthly_calendar' year=prev_month.year month=prev_month.month %}" class="btn btn-secondary me-2">
        Previous Month
      </a>
      <a href="{% url 'calendar:monthly_calendar' year=next_month.year month=next_month.month %}" class="btn btn-secondary">
        Next Month
      </a>
    </div>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Mon</th>
        <th scope="col">Tue</th>
        <th scope="col">Wed</th>
        <th scope="col">Thu</th>
        <th scope="col">Fri</th>
        <th scope="col">Sat</th>
        <th scope="col">Sun</th>
      </tr>
    </thead>
    <tbody>
      {% for week in calendar %}
        <tr>
          {% for day in week %}
            <td class="p-2">
              {% if day != 0 %}
                    <div class="day-box">
                        {{ day }}
                        {% with day_events=events_dict|default:{}|get:day %}
                            {% for event in day_events %}
                                <p class="mb-0">{{ event.content_object }}</p>
                            {% endfor %}
                        {% endwith %}
                    </div>
                {% endif %}
            </td>
          {% endfor %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}